In [1]:
# Calling libraries:
from __future__ import division
%matplotlib inline
import numpy as np, time, matplotlib.pyplot as plt, math, pandas, numpy.random as npr, multiprocessing as mp
from pylab import plot, show, legend
from time import time
from scipy.stats import *
from tqdm import trange
from ecology_functions import *

In [2]:
T = 25
I = 5  # number of locations
J = 3  # number of species
K = 2   # number of latent factors

In [3]:
lmbda = npr.randn(J,K)
alpha = npr.randn(J)
c = 0
phi = 0.5
logsigmasq = 0
x_0 = npr.randn(I,K)

theta = [alpha, lmbda, c, phi, logsigmasq]

In [4]:
n_particles = 5_000
rep = 10 

for r in range(rep) :
    Y, X = simulate_data(x_0, T, J, theta)
    _, _, grad_block = block_pf(Y, x_0, n_particles, theta, calc_grad=True)
    _, grad_boot, _, _ = bootstrap_PF_grad(x_0, n_particles, theta, Y, calc_grad=True)
    for i in range(5) :
        print(grad_block[i]/grad_boot[i])

  0%|          | 0/25 [00:00<?, ?it/s]

[1. 1. 1.]
[[ 0. -0.]
 [-0.  0.]
 [ 0. -0.]]
-0.7551402815944355
0.9899790342191112
0.9777854458114966


  0%|          | 0/25 [00:00<?, ?it/s]

[1. 1. 1.]
[[ 0. -0.]
 [-0.  0.]
 [ 0.  0.]]
-0.6454866098654026
0.8870629785030822
0.8924580617665057


  0%|          | 0/25 [00:00<?, ?it/s]

[1. 1. 1.]
[[-0.  0.]
 [-0.  0.]
 [-0.  0.]]
-2.5702341290461557
1.0713688357613478
1.1118367564696523


  0%|          | 0/25 [00:00<?, ?it/s]

[1. 1. 1.]
[[-0.  0.]
 [-0.  0.]
 [-0. -0.]]
0.14540839633473124
1.1565994577268033
1.0099974521238835


  0%|          | 0/25 [00:00<?, ?it/s]

[1. 1. 1.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
-0.037156741464162736
1.031579067672755
0.8628303071797006


  0%|          | 0/25 [00:00<?, ?it/s]

[1. 1. 1.]
[[ 0.  0.]
 [-0.  0.]
 [ 0. -0.]]
0.3726453173963876
1.2515016903081166
1.1219143863058167


  0%|          | 0/25 [00:00<?, ?it/s]

[1. 1. 1.]
[[ 0. -0.]
 [ 0.  0.]
 [ 0. -0.]]
0.5792062375896803
1.0710630293232084
0.9969132653417535


  0%|          | 0/25 [00:00<?, ?it/s]

[1. 1. 1.]
[[ 0. -0.]
 [ 0.  0.]
 [ 0. -0.]]
0.10118504478225909
1.0715370040998138
1.16002218352034


  0%|          | 0/25 [00:00<?, ?it/s]

[1. 1. 1.]
[[-0.  0.]
 [-0.  0.]
 [-0.  0.]]
27.630874919231136
1.1802034988917038
1.0542084960786002


100%|██████████| 25/25 [00:12<00:00,  1.98it/s]


[1. 1. 1.]
[[ 0.  0.]
 [ 0.  0.]
 [ 0. -0.]]
-0.8098773820964922
0.9302715198007979
1.0303622226612217
